name: qm9_test
description: eps -60, no BN, ne 64, lr 1, seq avg
data:
  path: /data/chem/qm9.xyz.tar
hyperparameters:
  learning_rate: 1e-4
  global_batch_size: 32
  num_emb: 64
  tb_epsilon: -60
searcher:
  name: single
  metric: validation_loss
  max_length:
      batches: 20000
  smaller_is_better: true
min_validation_period:
  batches: 500
entrypoint: qm9:QM9Trial
checkpoint_policy: best
checkpoint_storage:
  host_path: /mnt/bh1/scratch/det_checkpoints
  type: shared_fs
bind_mounts:
  - host_path: /mnt/ps/home/CORP/emmanuel.bengio/rs
    container_path: /run/determined/workdir/rs
  - host_path: /mnt/ps/home/CORP/emmanuel.bengio/lib/
    container_path: /run/determined/workdir/lib/
  - host_path: /mnt/bh1/data/
    container_path: /data
  - host_path: /mnt/bh1/scratch/maciej.sypetkowski/torch_home
    container_path: /torch_home
environment:
  image: gcr.io/eng-infrastructure/photosynthetic:maciek_dev
  add_capabilities:
    - IPC_LOCK
  force_pull_image: false
  environment_variables:
    - TORCH_HOME=/torch_home
    - LD_LIBRARY_PATH=/usr/local/mpi/lib/:$LD_LIBRARY_PATH
resources:
  resource_pool: dgx-pool
  agent_label: ampere
  priority: 1
#profiling:
#  enabled: true
