name: qm9_test
description: Z adam
data:
  h5_path: /data/chem/qm9/qm9.h5
  path: /data/chem/qm9/qm9.xyz.tar
hyperparameters:
  learning_rate: 5e-4
#    type: double
#    minval: 1e-4
#    maxval: 3e-4
#    count: 3
  global_batch_size: 128
  num_emb: 64
#    type: categorical
#    vals:
#      - 32
#      - 64
#      - 128
  tb_epsilon: -60
  reward_loss_multiplier: 1
  temperature_sample_dist: gamma
  temperature_dist_params: (1.5, 1.5)
  #temperature_sample_dist: beta
  #temperature_dist_params: (1.25, 2)
  #temperature_sample_dist: uniform
  #temperature_dist_params: (0.5, 8)
  num_data_loader_workers: 6
searcher:
  name: single #grid
  metric: validation_loss
  max_length:
      batches: 50000
  smaller_is_better: true
min_validation_period:
  batches: 500
entrypoint: qm9:QM9Trial
checkpoint_policy: best
checkpoint_storage:
  host_path: /mnt/bh1/scratch/det_checkpoints
  type: shared_fs
bind_mounts:
  - host_path: /mnt/ps/home/CORP/emmanuel.bengio/rs
    container_path: /run/determined/workdir/rs
  - host_path: /mnt/ps/home/CORP/emmanuel.bengio/lib/
    container_path: /run/determined/workdir/lib/
  - host_path: /mnt/bh1/data/
    container_path: /data
  - host_path: /mnt/bh1/scratch/maciej.sypetkowski/torch_home
    container_path: /torch_home
environment:
  image: gcr.io/eng-infrastructure/photosynthetic:maciek_dev
  add_capabilities:
    - IPC_LOCK
  force_pull_image: false
  environment_variables:
    - TORCH_HOME=/torch_home
    - LD_LIBRARY_PATH=/usr/local/mpi/lib/:$LD_LIBRARY_PATH
resources:
  resource_pool: dgx-pool
  agent_label: ampere
  priority: 1
  slots_per_trial: 1
#profiling:
#  enabled: true
